boards/firstproject/urls.py
from django.conf.urls import url
from django.contrib import admin

from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.home, name='home'),
    #url(r'^about/company/$', views.about_company, name='about_company'),
    #url(r'^(?P<username>[\w.@+-]+)/$', views.user_profile, name='user_profile'),
]

firstproject/urls.py
from django.conf.urls import url
from django.contrib import admin

from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.home, name='home'),
    #url(r'^about/company/$', views.about_company, name='about_company'),
    #url(r'^(?P<username>[\w.@+-]+)/$', views.user_profile, name='user_profile'),
]

urls.py
from django.conf.urls import url
from django.contrib import admin

from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.home, name='home'),
    #url(r'^about/company/$', views.about_company, name='about_company'),
    #url(r'^(?P<username>[\w.@+-]+)/$', views.user_profile, name='user_profile'),
]

boards/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')


    


boards/forms.py
from django import forms
from .models import Topic

#a model form associated with the Topic model
class NewTopicForm(forms.ModelForm): 
    message = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Topic

        '''
        'subject' refers to the subject field in Topic class
        define extra field 'message'
        which refers to the message in Post
        '''
        fields = ['subject', 'message'] 
        

boards/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User

#Views are Python functions that receive an HttpRequest object
#and return HttpResponse object.

from django.http import HttpResponse
from .models import Board, Topic, Post
from django.http import Http404
from .forms import NewTopicForm

def home(request):
    boards = Board.objects.all()
    boards_names = list()
    #already declared in python shell:
    #board = Board(name='Django', description='...')
    #board = Board(name='Python', descrition='...')

##    for board in boards:
##        boards_names.append(board.name)
##
##    response_html = '<br>'.join(boards_names)
    
##    return HttpResponse(response_html)
    return render(request, 'home.html', {'boards': boards})

def about(request):
    return render(request, 'about.html')

#keyword argument 'pk' must be matched with url pattern(?P<pk>\d+)
#'pk' = Primary Key
def board_topics(request, pk):
    try:
        board = Board.objects.get(pk=pk)
    except Board.DoesNotExist:
        raise Http404
    board = get_object_or_404(Board, pk=pk)
    return render(request, 'topics.html', {'board': board})
    
##def about_company(request):
##    return render(request, 'about_company.html', {'board': board})

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = User.objects.first() #get the currently logged in user

    #check if request is POST or GET
    if request.method == 'POST': #user is submitting data to server
        #passing the POST data to the form
        form = NewTopicForm(request.POST)
        #ask Django to verify data
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save() #save data to the database
            post = Post.objects.create(
                message =  form.cleaned_data.get('message'),
                topic = topic,
                created_by = user
            )

            #redirect to the created topic page
            return redirect('board_topics', pk = board.pk)
    else: #if request is a GET, initialize a new and empty form
        form = NewTopicForm()
    #have to update the new_topic.html to display errors properly   
    return render(request, 'new_topic.html', {'board': board, 'form': form})

##        subject = request.POST['subject']
##        message = request.POST['message']
##        
##        #get the currently login user
##        user = User.objects.first() 
##
##        #start a new topic
##        topic = Topic.objects.create(
##            subject = subject,
##            board = board, #this is ForeignKey(Board)
##            starter = user
##            )
##
##        #receive data from HTML
##        post = Post.objects.create(
##            message = message,
##            topic = topic,
##            created_by = user
##            )
##
            

    

templates/base.html
<!-- This is a master page -->

{% load static %}<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<!-- %block% tag used to reserve space
		("child" template which extends the master page),
		block title : setting a default value --> 
		<title>{% block title %}Django Boards{% endblock %}</title>
		<link href="https://fonts.googleapis.com/css?family=Unlock" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/app.css' %}">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<!--Back to the homepage-->
				<a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
			</div>
		</nav>
		
		<div class="container">
			<ol class="breadcrumb my-4">
				{% block breadcrumb %}
				{% endblock %}
			</ol>
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

templates/home.html
<!--tell Django to use base.html template as master page-->
	{% extends 'base.html' %} 
	
	{% block breadcrumb %}
		<li class="breadcrumb-item active">Boards</li>
	{% endblock %}
	
	{% block content %}
			<table class="table">
				<thead class="thead-dark">
					<tr><!--table row-->
					<!--header for this row-->
						<th>Board</th>
						<th>Posts</th>
						<th>Topics</th>
						<th>Last Post</th>
					</tr>
				</thead>
				<tbody><!---->
					{% for board in boards %}
					<tr>
						<td><!-- //table data -->
						<!-- Create navigation link to the topics page of given Board
							Tag % url % compose the applications URLs,
							first parameter 'board_topics' is the name of URL-->
							<a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
							<!-- <small style="color: #888">{{board.description}}</small> -->
							<small class="text-muted d-block">{{board.description}}</small>
						</td>
						<td class="align-middle">0</td>
						<td class="align-middle">0</td>
						<td></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>	
	{% endblock %}
	

<!--The old version-->
<!-- % load static % loading Static App template 
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Boards</title>
		<link rel="stylesheet" href="% static "css/bootstrap.min.css" %">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
	</head>
	<body>
		<div class="container">
			<ol class="breadcrumb my-4"> <ol> tag defines ordered list
				<li class="breadcrumb-item active">Boards</li> <li> defines list-item
			</ol>
		
		  -->

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
	<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
	<li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
	<li class="breadcrumb-item active">New Topic</li>
{% endblock %}

<!--raw HTML form created using CSS classes provided by Bootstrap 4-->
{% block content %}
	<!--Use 'method' attribute to instructs the browser 
	how to communicate with server: POST request types-->
	<form method="post">
		<!-- Django protects all POST requests using CSRF Token
		(Cross-Site Request Forgery Token) -->
		{% csrf_token %}
		<!--using the Forms API-->
		{{ form.as_p }}

		<!--The old version before creating form.py-->		
<!-- 		<div class="form-group">
			<label for="id_subject">Subject</label>
			<input type="text" class="form-control" id="id_subject" name="subject">
		</div>
		
		<div class="form-group">
			<label for="id_message">Message</label>
			<textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
		</div> -->
		<button type="submit" class="btn btn-success">Post</button>
	</form>
{% endblock %}	

templates/topics.html
<!--New version -->
	{% extends 'base.html' %}

	{% block title %}
		{{ board.name }} - {{ block.super}}
	{% endblock %}

	{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
		<li class="breadcrumb-item active">{{ board.name }}</li>
	{% endblock %}
	
	{% block content %}
		<!--button to the new topic-->
		<div  class="mb-4">
			<a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New Topic</a>
		</div>
		
		<table class="table">
			<thead class="thead-inverse">
				<tr> <!--table has 5 headers as 5 columns-->
					<th>Topic</th>
					<th>Starter</th>
					<th>Replies</th>
					<th>Views</th>
					<th>Last Update</th>
				</tr>
			</thead>
			
			<tbody>
				{% for topic in board.topics.all %}
					<tr>
						<td>{{ topic.subject }}</td>
						<td>{{ topic.starter.username }}</td> 
						<!--if you wanna have user's email, we can use 'topic.starter.email'-->
						<td>0</td>
						<td>0</td>
						<td>{{ topic.last_updated }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% endblock %}

<!--THIS IS THE OLD VERSION BEFORE 'BASE.HTML' IS CREATED-->
<!-- % load static %<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{ board.name }}</title>
		<link  rel="stylesheet" href="% static 'css/bootstrap.min.css' %">
	</head>
	<body>
		<div class="container">
			<ol class="breadcrumb my-4">
				<li class="breadcrumb-item">Boards</li>
				<li class="breadcrumb-item active">{{ board.name }}</li>
			</ol>
		</div>
	</body>
</html> -->